server:
  port: 8091
  servlet:
    encoding:
      charset: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookshop
    username: root
    password: Leandro2009*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  